from enum import Enum

class EventType(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_DEGRADATION = "PAYMENT_DEGRADATION"
    CART_ABANDONMENT = "CART_ABANDONMENT"
    CHECKOUT_DROPOFF = "CHECKOUT_DROPOFF"
    SUBSCRIPTION_PAYMENT_FAILURE = "SUBSCRIPTION_PAYMENT_FAILURE"
    SUBSCRIPTION_CHURN_RISK = "SUBSCRIPTION_CHURN_RISK"
    RECEIVABLE_OVERDUE = "RECEIVABLE_OVERDUE"
    MANDATE_FAILURE = "MANDATE_FAILURE"
    PROMISE_TO_PAY_DUE = "PROMISE_TO_PAY_DUE"
    PROMISE_TO_PAY_BROKEN = "PROMISE_TO_PAY_BROKEN"
    VOICE_RECOVERY_REQUIRED = "VOICE_RECOVERY_REQUIRED"
